import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  description: 'Global settings for your website, including navigation and social media links.',
  groups: [
    {name: 'navigation', title: 'Navigation', default: true},
    {name: 'social', title: 'Social Media'},
  ],
  fields: [
    // Navigation toggles for special pages
    defineField({
      name: 'showAgenda',
      title: 'Show Agenda Page',
      type: 'boolean',
      description: 'When enabled, the Agenda page appears in the navigation menu.',
      initialValue: true,
      group: 'navigation',
    }),
    defineField({
      name: 'agendaLabel',
      title: 'Agenda Menu Label',
      type: 'string',
      description: 'What this page is called in the navigation menu. Default: "Agenda".',
      initialValue: 'Agenda',
      group: 'navigation',
    }),
    defineField({
      name: 'agendaOrder',
      title: 'Agenda Menu Order',
      type: 'number',
      description: 'Position in the navigation menu. Lower numbers appear first.',
      initialValue: 20,
      group: 'navigation',
    }),
    defineField({
      name: 'showStays',
      title: 'Show Stays Page',
      type: 'boolean',
      description: 'When enabled, the Stays page appears in the navigation menu.',
      initialValue: true,
      group: 'navigation',
    }),
    defineField({
      name: 'staysLabel',
      title: 'Stays Menu Label',
      type: 'string',
      description: 'What this page is called in the navigation menu. Default: "Stays".',
      initialValue: 'Stays',
      group: 'navigation',
    }),
    defineField({
      name: 'staysOrder',
      title: 'Stays Menu Order',
      type: 'number',
      description: 'Position in the navigation menu. Lower numbers appear first.',
      initialValue: 30,
      group: 'navigation',
    }),
    defineField({
      name: 'showJourney',
      title: 'Show Journey Page',
      type: 'boolean',
      description: 'When enabled, the Journey page appears in the navigation menu.',
      initialValue: true,
      group: 'navigation',
    }),
    defineField({
      name: 'journeyLabel',
      title: 'Journey Menu Label',
      type: 'string',
      description: 'What this page is called in the navigation menu. Default: "Journey".',
      initialValue: 'Journey',
      group: 'navigation',
    }),
    defineField({
      name: 'journeyOrder',
      title: 'Journey Menu Order',
      type: 'number',
      description: 'Position in the navigation menu. Lower numbers appear first.',
      initialValue: 40,
      group: 'navigation',
    }),
    defineField({
      name: 'showMembers',
      title: 'Show Members Page',
      type: 'boolean',
      description: 'When enabled, the Members page appears in the navigation menu.',
      initialValue: true,
      group: 'navigation',
    }),
    defineField({
      name: 'membersLabel',
      title: 'Members Menu Label',
      type: 'string',
      description: 'What this page is called in the navigation menu. Default: "Members".',
      initialValue: 'Members',
      group: 'navigation',
    }),
    defineField({
      name: 'membersOrder',
      title: 'Members Menu Order',
      type: 'number',
      description: 'Position in the navigation menu. Lower numbers appear first.',
      initialValue: 50,
      group: 'navigation',
    }),
    // Social media
    defineField({
      name: 'instagramUrl',
      title: 'Instagram URL',
      type: 'url',
      description: 'Your Instagram profile URL, e.g. "https://instagram.com/yourhandle".',
      initialValue: 'https://instagram.com',
      group: 'social',
    }),
    defineField({
      name: 'showInstagram',
      title: 'Show Instagram Link',
      type: 'boolean',
      description: 'When enabled, an Instagram link appears in the navigation.',
      initialValue: true,
      group: 'social',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'Site Settings',
        subtitle: 'Global navigation and social media settings',
      }
    },
  },
})
